// Descrição curta e palavras de busca de cada configuração do painel.
// HINTS completa o `hint` dos campos que ainda não têm explicação; KEYWORDS são sinônimos que o dono costuma digitar
// (a busca ignora acento e maiúsculas). Mantidos aqui, fora do schema, para não misturar texto de ajuda com regra.

export const HINTS: Record<string, string> = {
  fontChoice: 'Letra usada em todo o site (textos, botões e títulos).',
  bgTone: 'Cor de fundo atrás dos cards. Sempre clara, para o texto continuar legível.',
  gridCols: 'Quantos produtos aparecem lado a lado em telas grandes. No celular são sempre 2.',
  homeLayout: 'Escolha o desenho da página inicial. Dá para trocar quando quiser; os produtos e textos continuam os mesmos.',
  customBandRows: 'Em que ponto da lista de produtos a faixa "Peça personalizada" aparece.',
  showHowCustom: 'Mostra, ao lado dos 3 passos, um convite para pedir uma peça sob medida.',
  howTitle: 'Título acima dos 3 passos que explicam como pedir.',
  stepOneTitle: 'Título curto do primeiro passo.',
  stepOneText: 'Explique o primeiro passo em uma ou duas frases.',
  stepTwoTitle: 'Título curto do segundo passo.',
  stepTwoText: 'Explique o segundo passo em uma ou duas frases.',
  stepThreeTitle: 'Título curto do terceiro passo.',
  stepThreeText: 'Explique o terceiro passo em uma ou duas frases.',
  howCustomText: 'Frase do convite para pedido personalizado, ao lado dos passos.',
  logoShape: 'Como a logo é recortada no topo: como enviada, cantos arredondados ou círculo.',
  brandLayout: 'Nome ao lado da logo ou abaixo dela.',
  nameFont: 'Letra do nome da loja no topo. Só vale para o nome, não para o resto do site.',
  nameSize: 'Altura das letras do nome no computador.',
  nameItalic: 'Deixa o nome da loja inclinado.',
  nameCase: 'Mostra o nome como foi digitado, em MAIÚSCULAS ou em minúsculas.',
  nameSpacing: 'Distância entre as letras do nome: apertado, normal ou aberto.',
  nameColorMode: 'Usa a cor do texto do site, a cor principal da loja ou uma cor que você escolher.',
  bannerEnabled: 'Liga ou desliga a faixa de aviso sem apagar o texto.',
  bannerColor: 'Cor de fundo da faixa. Vazio = cor principal da loja.',
  storeName: 'Aparece no topo, no rodapé, na aba do navegador e nas mensagens.',
  catalogTitle: 'Título grande da página inicial.',
  catalogSubtitle: 'Frase de apresentação logo abaixo do título da página inicial.',
  showCardBadge: 'Mostra uma etiqueta pequena acima do título da faixa de peça personalizada.',
  cardBadge: 'Texto da etiqueta pequena da faixa.',
  cardTitle: 'Título da faixa que convida o cliente a pedir uma peça personalizada.',
  cardText: 'Texto da faixa de peça personalizada.',
  cardButton: 'Texto do botão da faixa.',
  customTitle: 'Título da página onde o cliente descreve a peça que quer.',
  customIntro: 'Explicação abaixo do título da página de peça personalizada.',
  customSuccess: 'Mensagem que o cliente vê depois de enviar a solicitação.',
  menuHome: 'Nome do botão do menu que leva à vitrine.',
  menuAbout: 'Nome do botão do menu que leva à página Sobre.',
  menuCustom: 'Nome do botão do menu que leva ao pedido de peça personalizada.',
  pausedMessage: 'Texto mostrado ao cliente enquanto os pedidos estão pausados.',
  notesEnabled: 'Mostra o campo "Observações" no carrinho. Desligado, o cliente não escreve recados.',
  addToCartLabel: 'Texto do botão principal da janela do produto.',
  cartTitle: 'Título da gaveta do carrinho.',
  cartEmpty: 'Mensagem quando o carrinho não tem nada.',
  cartIntro: 'Frase acima dos campos de nome e WhatsApp.',
  orderDoneTitle: 'Título da tela que aparece depois que o pedido é enviado.',
  orderDoneText: 'Mensagem da tela de pedido enviado.',
  whatsappButton: 'Texto do botão que abre a conversa no WhatsApp depois do pedido.',
  aboutTitle: 'Título da página Sobre.',
  aboutImage: 'Foto no alto da página Sobre.',
  showFeatured: 'Mostra a seção de produtos em destaque no topo da vitrine.',
  featuredTitle: 'Título da seção de destaques.',
  showPopular: 'Mostra a seção dos produtos mais pedidos no topo da vitrine.',
  popularTitle: 'Título da seção de mais pedidos.',
  newTitle: 'Título da seção de novidades.',
  defaultSort: 'Em que ordem os produtos aparecem quando o cliente ainda não escolheu.',
  showSearch: 'Mostra o campo de busca na vitrine.',
  lowStockText: 'Texto do selo automático de poucas unidades.',
  relatedTitle: 'Título do bloco de produtos parecidos, na janela do produto.',
  socialInstagram: 'Seu @ ou o link do perfil. Aparece no rodapé.',
  socialTiktok: 'Seu @ ou o link do perfil. Aparece no rodapé.',
  socialFacebook: 'Link da sua página. Aparece no rodapé.',
  socialYoutube: 'Link do seu canal. Aparece no rodapé.',
};

// Sinônimos para a busca: o dono digita "zap", "frete", "logo", "tamanho da letra"…
export const KEYWORDS: Record<string, string> = {
  whatsapp: 'zap zapzap telefone celular numero contato pedidos',
  email: 'e-mail correio contato',
  storeName: 'nome loja titulo marca',
  primaryColor: 'cor tema azul botoes marca paleta',
  fontChoice: 'letra tipografia fonte texto',
  bgTone: 'fundo cor pano de fundo',
  cardStyle: 'cantos bordas arredondado raio quadrado',
  gridCols: 'colunas grade produtos por linha',
  darkMode: 'escuro noturno claro tema dark',
  logoUrl: 'logotipo imagem marca topo',
  faviconUrl: 'icone aba navegador',
  deliveryEnabled: 'frete entrega retirada correio envio',
  deliveryNote: 'frete prazo entrega envio',
  minOrder: 'minimo pedido valor compra',
  ordersPaused: 'pausar ferias fechado parar pedidos',
  hidePrices: 'preco valores esconder sob consulta',
  stockControl: 'estoque quantidade disponivel esgotado',
  lowStockBadge: 'ultimas unidades acabando selo estoque baixo',
  badgeColor: 'selo etiqueta cor',
  seoTitle: 'google busca titulo compartilhar',
  seoDescription: 'google busca descricao resumo',
  seoImage: 'imagem compartilhar whatsapp preview link',
  footerText: 'rodape horario atendimento aviso',
  privacyText: 'lgpd dados privacidade politica',
  bannerText: 'aviso faixa promocao topo comunicado',
  heroImage: 'capa banner imagem topo home',
  homeLayout: 'modelo layout pagina inicial vitrine bancada',
  showSearch: 'busca pesquisar procurar',
  defaultSort: 'ordem ordenar recentes preco',
  relatedEnabled: 'relacionados sugestoes parecidos voce tambem pode gostar',
  customEnabled: 'personalizado sob medida orcamento encomenda',
  leadTimeEnabled: 'prazo producao entrega dias',
  aurasEnabled: 'aura brilho efeito',
  modelLinkEnabled: 'modelo 3d arquivo stl link',
  socialInstagram: 'instagram insta rede social',
  socialTiktok: 'tiktok rede social',
  socialFacebook: 'facebook rede social',
  socialYoutube: 'youtube video rede social',
  orderMessageIntro: 'mensagem whatsapp pedido abertura texto',
  customMessage: 'mensagem whatsapp personalizado texto',
  addToCartLabel: 'botao comprar carrinho orcamento adicionar',
};
